title: Damien Waits
description: Laboratory Technician
site_title: 'Aint Got No Social Medias'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: DamienWaits
blog_url:
email: dsw0002@gmail.com
keybase_username:
twitter_username:
reddit_username:

# absolute or relative
profile_picture: assets/images/Portrait-_clipped.jpg

# Google Analytics ID
google_analytics: 
